version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    working_dir: /app
    volumes:
      - .:/app
    command: ["python", "19_03.py"]

